### ISSUE TITLE
Cache twitter handles

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#40]
## Context

Often, people are viewing the same websites repeatedly and twitter handles change extremely infrequently, so we can use an cache backed by `localStorage` to persist twitter handles that we've already fetched so that we need not make additional network requests for them.

## Todo

- [ ] For [fetchTwitterHandle](https://github.com/morehumaninternet/roar-extension/blob/fd3494ab062189c013f4370dd3d59b2088d47b22/src/background/api.ts#L53) if the twitter_handle exists, add it to `localStorage` with the key `twitter-handle-${host}`
- [ ] Prior to `makeHandleRequest`, check if a twitter handle already exists in localStorage and dispatch `dispatchBackgroundActions.fetchHandleSuccess` if so
- [ ] Add unit tests showing this behavior is working
