### ISSUE TITLE
Use Alert component for non-host pages

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#42]
## Context 

We currently [render a paragraph tag](https://github.com/morehumaninternet/roar-extension/blob/fd3494ab062189c013f4370dd3d59b2088d47b22/src/popup/app.tsx#L39) when there's no host for the given tab (such as when you're on the chrome://extensions page)

When #38 is done, we'll have an alert component that we can use instead. The alert component should be the only thing displayed and clicking the x should close the popup entirely.

## Todo

- [ ] Use the `<Alert />` component as the app when there is no host for the tab
- [ ] Ensure no other aspect of the page loads (no blue background)
- [ ] Clicking the close button should call `window.close` instead of `dismissAlert`
