### ISSUE TITLE
Limit feedback to 280 characters

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#48]
## Context

Tweets are limited to 280 characters, so we need to impose this limitation upstream, so we'll use a component similar to the one Twitter uses to indicate to the user when they're approaching the character limit

## Todo

- [x] Add a `characters: { total: number, remaining: number, proportion: number }` property to the [FeedbackState type](https://github.com/morehumaninternet/roar-extension/blob/fd3494ab062189c013f4370dd3d59b2088d47b22/src/types.ts#L48)
- [x] Whenever the feedback is cleared the `characters` should be set to `{ total: 0, remaining: 280, proportion: 0 }`
- [x] Whenever [updateEditorState](https://github.com/morehumaninternet/roar-extension/blob/fd3494ab062189c013f4370dd3d59b2088d47b22/src/background/responders.ts#L72) is called, update the characterLimit accordingly
- [x] Add a `<CharacterLimit>` react component that appears next to the Post button whenever `characters.total > 0`, but no component if no characters have been input
- [x] Have the colored region of the <CharacterLimit>` fill in clockwise as the `characters.proportion` increases from 0 to 1, taking up 75% of the circle when `characters.proportion == 0.75`
- [x] When there are 20 characters or fewer remaining, include the number of characters remaining in the center and change the color to yellow.
- [x] When there are 0 characters or fewer remaining, remove the circle and put the number in pink
- [x] When there are fewer than zero characters remaining disable the post button, setting its opacity to 0.65

<img width="278" alt="image" src="https://user-images.githubusercontent.com/6589960/99296143-4a8acf00-2814-11eb-9998-b68b049e5ff7.png">
<img width="490" alt="image" src="https://user-images.githubusercontent.com/6589960/99297398-3647d180-2816-11eb-81ec-6bfc4d2f81aa.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/6589960/99297471-4e1f5580-2816-11eb-9821-f056621ad16d.png">

**Comment by shachar-langer** [comment]
Resolved by #83
