### ISSUE TITLE
Toggle help states on push of help button

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#52]
## Context

Users might have ideas/feedback/suggestions for roar itself, so we want to create a way for them to voice that feedback from within the extension itself.

## Todo

- [ ] Include a `<Help>` component (represented as a question mark) that toggles whether the help is on or not
- [ ] Update the `AppState` to include a separate help feedback whose hostTwitterHandle is `@roarmhi`  
- [ ] When in a helpClicked state, the feedback being edited, no matter the tab, is the `extensionFeedback` and clicking post posts that feedback instead
