### ISSUE TITLE
Support uploading files

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#58]
## Context

The add image button should allow a user to upload an image file, which will be appended to the list of screenshots that get sent as part of the tweet

## Todo

- [ ] Support uploading a file when the screenshot button is clicked
- [ ] Non-image file extensions are rejected with an alert, see #38
- [ ] Files greater than 5MB are rejected, per [twitter's API limitations](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)
- [ ] Uploaded images appear like screenshots and are posted like screenshots
- [ ] Unit tests confirm these behaviors
