### ISSUE TITLE
Check whether the user is logged in when the extension first loads

### ISSUE THREAD

**Issue by will-weiss** [morehumaninternet/roar-extension#82]
## Context
The extension should not require you to log in if you already have a functional cookie

Requires https://github.com/morehumaninternet/roar-server/issues/31

## Todo
- [ ] When the application first loads make a request to /v1/me
- [ ] If it 200s transition to authenticated state with the correct userPhoto
- [ ] If it 401s stay in an unauthenticated state
